// <auto-generated />
using System.Collections.Generic;
using CardsService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CardsService.Migrations
{
    [DbContext(typeof(ThemeContext))]
    [Migration("20260604072654_SyncMigration")]
    partial class SyncMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CardsService.ThemeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Words")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("Words");

                    b.HasKey("Id");

                    b.ToTable("Themes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Theme = "Education",
                            Words = new List<string> { "Gymnasium", "Student", "Teacher", "Notebook", "Diploma", "Credit", "Lecture", "Journal", "Marker", "Briefcase", "Discipline", "University", "Exam" }
                        },
                        new
                        {
                            Id = 2,
                            Theme = "Sport",
                            Words = new List<string> { "Whistle", "Medal", "Timeout", "Fan", "Season Ticket", "Equipment", "Disqualification", "Overtime", "Grandstand", "Mascot", "Standard", "Rank", "Championship" }
                        },
                        new
                        {
                            Id = 3,
                            Theme = "Travelling",
                            Words = new List<string> { "Ticket", "Suitcase", "Passport", "Layover", "Engine", "Route", "Flight attendant", "Fellow traveler", "Security check", "Hitchhiking", "Customs" }
                        },
                        new
                        {
                            Id = 4,
                            Theme = "Plants",
                            Words = new List<string> { "Rose", "Tulip", "Cactus", "Sunflower", "Daisy", "Birch", "Oak", "Palm Tree", "Fir Tree", "Bamboo", "Nettle", "Dandelion", "Lotus", "Fern", "Maple", "Lily", "Reed", "Aloe", "Vine", "Sequoia", "Moss", "Lilac", "Jasmine", "Lavender", "Orchid" }
                        },
                        new
                        {
                            Id = 5,
                            Theme = "Animals",
                            Words = new List<string> { "Lion", "Tiger", "Elephant", "Giraffe", "Zebra", "Panda", "Kangaroo", "Penguin", "Shark", "Dolphin", "Crocodile", "Turtle", "Snake", "Eagle", "Parrot", "Owl", "Bear", "Wolf", "Fox", "Squirrel", "Monkey", "Hippopotamus", "Rhinoceros", "Camel" }
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
